In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [2]:
bwght = pd.read_csv('BWGHT.CSV')

In [3]:
import sqlite3
#use sql

In [4]:
con = sqlite3.connect("bwght.db")
# con = sqlite3.connect(":memory:")
c = con.cursor()


In [5]:
bwght.to_sql('BTABLE',con)

In [8]:
c.execute('SELECT * FROM BTABLE WHERE cigs=50')
print(c.fetchall())

[(1303, 27.5, 2.5, 109.4, 90, None, 12.0, 5, 1, 0, 50, 4.49981, 5.625, 2.5, 3.314186)]


In [10]:
c.execute('SELECT * FROM BTABLE WHERE cigs>20')
for item in c.fetchall():
    print(item)
#可以分行显示

(74, 18.5, 21.0, 127.7, 115, 3.0, 12.0, 1, 0, 0, 40, 4.744932, 7.1875, 2.0, 2.917771)
(121, 6.5, 10.0, 126.4, 122, None, 10.0, 1, 1, 1, 40, 4.804021, 7.625, 2.0, 1.871802)
(298, 27.5, 24.0, 139.8, 81, 13.0, 12.0, 4, 0, 1, 40, 4.394449, 5.0625, 2.0, 3.314186)
(435, 37.5, 34.0, 145.1, 116, 13.0, 14.0, 1, 1, 1, 30, 4.75359, 7.25, 1.5, 3.6243410000000003)
(513, 11.5, 16.0, 130.7, 91, 8.0, 10.0, 1, 1, 1, 30, 4.510859, 5.6875, 1.5, 2.4423470000000003)
(616, 22.5, 25.0, 133.0, 136, 14.0, 8.0, 1, 1, 1, 40, 4.912655, 8.5, 2.0, 3.113515)
(882, 22.5, 2.0, 107.6, 94, 8.0, 8.0, 2, 0, 1, 30, 4.543295, 5.875, 1.5, 3.113515)
(894, 2.5, 18.0, 120.5, 102, None, 10.0, 1, 0, 1, 30, 4.624973000000001, 6.375, 1.5, 0.9162908000000001)
(895, 3.5, 18.0, 120.5, 138, None, 10.0, 3, 1, 0, 30, 4.9272540000000005, 8.625, 1.5, 1.2527629999999998)
(976, 5.5, 23.0, 133.4, 89, 9.0, 8.0, 2, 1, 0, 40, 4.488636, 5.5625, 2.0, 1.704748)
(1239, 0.5, 26.0, 137.0, 121, None, 12.0, 2, 1, 0, 46, 4.795791, 7.5625, 2.3, -0.6931472

In [11]:
def hailstone(x):
    step = 0
    while x!=1:
        step += 1
        x = x/2 if x%2==0 else 3*x+1
    return step

In [13]:
con.create_function('hs',1,hailstone)
# 1= take 1 argument not 2
c.execute('SELECT hs(cigs), cigs FROM BTABLE WHERE cigs>20')
#用这些数字 放进hali看多久可以循环
for item in c.fetchall():
    print(item)

(8, 40)
(8, 40)
(8, 40)
(18, 30)
(18, 30)
(8, 40)
(18, 30)
(18, 30)
(18, 30)
(8, 40)
(16, 46)
(8, 40)
(24, 50)


In [14]:
class geomean:
    def __init__(self): # Constructor
        self.sum = 0
        self.count = 0
    def step(self,value): # What to do when we get a new value
        self.sum += np.log(value)
#use log to avoid to big value
        self.count += 1
    def finalize(self):
        return np.exp(self.sum/self.count)
#define a function

In [15]:
con.create_aggregate("GEO",1,geomean)
#use last function
c.execute('SELECT GEO(bwght),cigs,COUNT(bwght) FROM BTABLE GROUP BY cigs;')
for item in c.fetchall():
    print(item)

(118.12914912512608, 0, 1176)
(122.01151015653141, 1, 3)
(108.25224006111848, 2, 4)
(114.32987300163663, 3, 7)
(108.60626107277508, 4, 9)
(112.90200845344134, 5, 19)
(121.44933131428813, 6, 6)
(119.16422565354631, 7, 4)
(87.69083957636508, 8, 5)
(127.99999999999997, 9, 1)
(110.78738483467163, 10, 55)
(105.91537925146471, 12, 5)
(106.73221579113947, 15, 19)
(108.05121183968193, 20, 62)
(106.91073090784444, 30, 5)
(104.74271003586932, 40, 6)
(121.00000000000003, 46, 1)
(90.0, 50, 1)


In [77]:
con.create_aggregate("GEO2",1,geomean2)
c.execute('SELECT GEO2(bwght),cigs,COUNT(bwght) FROM BTABLE WHERE cigs>0 GROUP BY cigs ;')
for item in c.fetchall():
    print(item)

(122.01151015653136, 1, 3)
(108.25224006111847, 2, 4)
(114.32987300163668, 3, 7)
(108.60626107277498, 4, 9)
(112.90200845344124, 5, 19)
(121.44933131428802, 6, 6)
(119.16422565354631, 7, 4)
(87.69083957636506, 8, 5)
(128.0, 9, 1)
(110.7873848346715, 10, 55)
(105.9153792514647, 12, 5)
(106.73221579113957, 15, 19)
(108.05121183968178, 20, 62)
(106.91073090784451, 30, 5)
(104.74271003586931, 40, 6)
(121.0, 46, 1)
(90.0, 50, 1)


In [16]:
con.commit()
con.close()

In [20]:
#bootstrapping
xdata = pd.concat((bwght['cigs'],bwght['faminc']),1).values
xdata = sm.add_constant(xdata)
ydata = bwght['bwght']
model = smf.OLS(ydata,xdata).fit()
beta = model.params
resid = ydata-model.predict()
beta

const    116.974130
x1        -0.463408
x2         0.092765
dtype: float64

In [21]:
#beta[1] = 0.0
bstar = np.zeros((10000,3))
for isim in range(10000):
    sample =  np.random.randint(low=0,high=1388,size=(1388,))
#a simple without replacement
    xxdata = xdata[sample]
    yydata = xxdata.dot(beta)+resid[sample]
    model = smf.OLS(yydata,xxdata).fit()
    bstar[isim,:] = model.params
bstar

array([[ 1.18220153e+02, -3.84398198e-01,  5.97022291e-02],
       [ 1.15994361e+02, -5.28946526e-01,  1.21711117e-01],
       [ 1.17228134e+02, -6.04815040e-01,  9.03409114e-02],
       ...,
       [ 1.17150948e+02, -3.14383015e-01,  6.01915145e-02],
       [ 1.18289420e+02, -4.59705833e-01,  5.92096752e-02],
       [ 1.18860516e+02, -5.33689246e-01,  4.27581678e-02]])

In [105]:
np.set_printoptions(suppress=True)
bstar[:,0].sort()
bstar[:,1].sort()
bstar[:,2].sort()
print(bstar[int(10000*0.025)])
print(bstar[int(10000*0.975)])
#confidance interval for beta 0 1 2   we can see if zero in to see significant   all significant here
#

[ 114.96070174   -0.17746492    0.03597279]
[ 118.9930044     0.16916835    0.14896821]


In [118]:
xdata = pd.concat((bwght['cigs'],bwght['faminc']),1).values
xdata = sm.add_constant(xdata)
ydata = bwght['bwght'].values
model = smf.OLS(ydata,xdata).fit()
beta = model.params
resid = ydata-model.predict()
model.tvalues

array([ 111.51182089,   -5.06031465,    3.17819498])

In [114]:
beta = np.zeros((3,))
tstar = np.zeros((10000,3))
for isim in range(10000):
    sample =  np.random.randint(low=0,high=1388,size=(1388,))
    xxdata = xdata[sample]
    yydata = xxdata.dot(beta)+resid[sample]
    model = smf.OLS(yydata,xxdata).fit()
    tstar[isim,:] = model.tvalues
tstar[:,0].sort()
tstar[:,1].sort()
tstar[:,2].sort()
print(tstar[int(10000*0.025)])
print(tstar[int(10000*0.975)])

[-1.94493614 -1.91895985 -1.91704485]
[ 1.92886679  1.90037637  1.89645557]


[-1.9272547  -1.89883774 -1.90314497]
[ 1.9493734   1.86575141  1.9077566 ]
